# This file is meant to be sourced.
# shellcheck disable=SC2034

project=randomizer
go_src=../cmd/randomizer-lambda

params_usage="$(cat <<EOF
  SlackToken=<token>  The token generated by Slack to authenticate webhook
                      requests.
EOF
)"

print-stack-output () (
  stack_name="$1"
  echo "The Slack webhook is available at the following URL:"
  aws cloudformation describe-stacks \
    --stack-name "$stack_name" \
    --output text \
    --query 'Stacks[0].Outputs[0].OutputValue'
)
