AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Description: A randomizer slash command for Slack, with support for saving groups and more

Parameters:
  SlackTokenSSMPath:
    Description: >-
      Path to the Slack slash command verification token in the AWS SSM
      Parameter Store, with no leading slash
    Type: String
  XRayTracingEnabled:
    Description: If 'true', turn on X-Ray tracing for all requests
    Type: String
    Default: 'true'
  ImageUri:
    Description: The container image for the Lambda function to run
    Type: String

Conditions:
  HasXRayTracingEnabled: !Equals [!Ref XRayTracingEnabled, 'true']

Resources:
  GroupsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: Partition
          KeyType: HASH
        - AttributeName: Group
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: Partition
          AttributeType: S
        - AttributeName: Group
          AttributeType: S
      BillingMode: PAY_PER_REQUEST

  Function:
    Type: AWS::Serverless::Function
    Properties:
      Description: A randomizer slash command for Slack, with support for saving groups and more
      Architectures: [arm64]
      PackageType: Image
      ImageUri: !Ref ImageUri
      Tracing: !If [HasXRayTracingEnabled, Active, PassThrough]
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref GroupsTable
          SLACK_TOKEN_SSM_PATH: !Sub '/${SlackTokenSSMPath}'
          AWS_CLIENT_XRAY_TRACING: !If [HasXRayTracingEnabled, '1', !Ref AWS::NoValue]
      Events:
        ApiGet:
          Type: Api
          Properties:
            Path: '/'
            Method: GET
        ApiPost:
          Type: Api
          Properties:
            Path: '/'
            Method: POST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GroupsTable
        - SSMParameterReadPolicy:
            ParameterName: !Ref SlackTokenSSMPath

Outputs:
  ApiUrl:
    Description: URL for the Slack slash command integration
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
