AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Description: A randomizer slash command for Slack, with support for saving groups and more

Parameters:
  SlackToken:
    Description: The authentication token created by Slack for the slash command
    Type: String

Resources:
  GroupsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: Partition
          KeyType: HASH
        - AttributeName: Group
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: Partition
          AttributeType: S
        - AttributeName: Group
          AttributeType: S
      BillingMode: PAY_PER_REQUEST

  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: A randomizer slash command for Slack, with support for saving groups and more
      Runtime: go1.x
      CodeUri: ./dist
      Handler: randomizer-lambda
      Environment:
        Variables:
          SLACK_TOKEN: !Ref SlackToken
          DYNAMODB_TABLE: !Ref GroupsTable
      Events:
        ApiGet:
          Type: Api
          Properties:
            Path: '/'
            Method: GET
        ApiPost:
          Type: Api
          Properties:
            Path: '/'
            Method: POST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GroupsTable

Outputs:
  ApiUrl:
    Description: URL for the Slack slash command integration
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
