AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Description: A randomizer slash command for Slack, with support for saving groups and more

Parameters:
  SlackToken:
    Description: The authentication token created by Slack for the slash command
    Type: String
  SlackCommandName:
    Description: The name of the command to display in help output in Slack
    Type: String
    Default: '/randomize'
  ReadCapacityUnits:
    Description: The number of read capacity units to set on the DynamoDB table
    Type: Number
    Default: '10'
  WriteCapacityUnits:
    Description: The number of write capacity units to set on the DynamoDB table
    Type: Number
    Default: '10'

Resources:
  GroupsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: Partition
          KeyType: HASH
        - AttributeName: Group
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: Partition
          AttributeType: S
        - AttributeName: Group
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref ReadCapacityUnits
        WriteCapacityUnits: !Ref WriteCapacityUnits

  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: A randomizer slash command for Slack, with support for saving groups and more
      Runtime: go1.x
      CodeUri: ./dist
      Handler: slack-lambda-handler
      Environment:
        Variables:
          SLACK_TOKEN: !Ref SlackToken
          SLACK_COMMAND_NAME: !Ref SlackCommandName
          DYNAMODB_TABLE: !Ref GroupsTable
      Events:
        ApiGet:
          Type: Api
          Properties:
            Path: '/'
            Method: GET
        ApiPost:
          Type: Api
          Properties:
            Path: '/'
            Method: POST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GroupsTable

Outputs:
  ApiUrl:
    Description: URL for the Slack slash command integration
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
