package slack

import "context"

// TokenProvider provides the value of the slash command verification token
// generated by Slack.
type TokenProvider func(ctx context.Context) ([]byte, error)

// StaticToken uses token as the expected value of the verification token.
func StaticToken(token []byte) TokenProvider {
	return func(_ context.Context) ([]byte, error) {
		return token, nil
	}
}
