# Pre-built container images are provided on a BEST-EFFORT basis, with no
# guarantee of continued support.
---
name: Mainline
on:
  push:
    branches: [main]
jobs:
  mainline:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Go
      uses: actions/setup-go@v3
      with: { go-version: "1.21" }
    - name: Run Tests
      run: go test -v -race ./...
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: |
          ghcr.io/ahamlinman/randomizer:latest
          ghcr.io/ahamlinman/randomizer:${{ github.sha }}
        platforms: |
          linux/amd64
          linux/arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max
